[package]
name = "zinc-kernel"
version = "4.0.2"
edition = "2024"

[[bin]]
name = "zinc-kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
zcore-drivers = { path = "../zcore/drivers" }
zcore-types = { path = "../zcore/types" }
zcore-constants = { path = "../zcore/constants" }
brass = { path = "../shell" }
zcore-memory = { path = "../zcore/memory" }